
workflows:
  flutter-zip-build:
    name: Flutter ZIP Build
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - unzip ganesha_mantra_app_full.zip -d ganesha_mantra_app
      - cd ganesha_mantra_app
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - ganesha_mantra_app/build/app/outputs/flutter-apk/app-release.apk
