"""
Demo / sample data for testing the report generator without live internet.
Run with: python -m finance_scraper.main --demo
"""

from typing import Any


def get_demo_data() -> dict[str, Any]:
    """Return realistic sample data for all report sections."""
    return {
        "indices": [
            {"name": "NIFTY 50", "last": "23,482.15", "change": "+142.30",
             "pct_change": "0.61", "open": "23,350.00", "high": "23,510.45",
             "low": "23,310.20", "prev_close": "23,339.85"},
            {"name": "SENSEX", "last": "77,312.48", "change": "+465.22",
             "pct_change": "0.61", "open": "76,890.00", "high": "77,405.00",
             "low": "76,750.30", "prev_close": "76,847.26"},
            {"name": "NIFTY BANK", "last": "49,875.60", "change": "+312.45",
             "pct_change": "0.63", "open": "49,600.00", "high": "49,920.00",
             "low": "49,520.10", "prev_close": "49,563.15"},
            {"name": "INDIA VIX", "last": "13.42", "change": "-0.58",
             "pct_change": "-4.14", "open": "14.00", "high": "14.12",
             "low": "13.35", "prev_close": "14.00"},
            {"name": "NIFTY IT", "last": "38,210.50", "change": "+285.75",
             "pct_change": "0.75", "open": "37,950.00", "high": "38,290.00",
             "low": "37,890.00", "prev_close": "37,924.75"},
            {"name": "NIFTY MIDCAP 100", "last": "52,430.80", "change": "-185.20",
             "pct_change": "-0.35", "open": "52,700.00", "high": "52,780.00",
             "low": "52,350.00", "prev_close": "52,616.00"},
            {"name": "NIFTY SMALLCAP 100", "last": "16,245.30", "change": "-92.10",
             "pct_change": "-0.56", "open": "16,380.00", "high": "16,410.00",
             "low": "16,200.00", "prev_close": "16,337.40"},
            {"name": "NIFTY FIN SERVICE", "last": "22,115.00", "change": "+178.55",
             "pct_change": "0.81", "open": "21,950.00", "high": "22,150.00",
             "low": "21,900.00", "prev_close": "21,936.45"},
            {"name": "NIFTY AUTO", "last": "24,560.75", "change": "+95.30",
             "pct_change": "0.39", "open": "24,480.00", "high": "24,610.00",
             "low": "24,420.00", "prev_close": "24,465.45"},
            {"name": "NIFTY PHARMA", "last": "19,872.40", "change": "+210.80",
             "pct_change": "1.07", "open": "19,680.00", "high": "19,910.00",
             "low": "19,640.00", "prev_close": "19,661.60"},
            {"name": "NIFTY METAL", "last": "8,235.60", "change": "-45.30",
             "pct_change": "-0.55", "open": "8,300.00", "high": "8,340.00",
             "low": "8,200.00", "prev_close": "8,280.90"},
            {"name": "NIFTY ENERGY", "last": "34,520.15", "change": "+125.60",
             "pct_change": "0.37", "open": "34,400.00", "high": "34,580.00",
             "low": "34,350.00", "prev_close": "34,394.55"},
            {"name": "NIFTY REALTY", "last": "982.45", "change": "+12.30",
             "pct_change": "1.27", "open": "972.00", "high": "985.00",
             "low": "968.00", "prev_close": "970.15"},
        ],
        "fii_dii": {
            "fii": {
                "buy_value": "12,845.32",
                "sell_value": "14,231.67",
                "net_value": "-1386.35",
                "date": "07-Feb-2026",
            },
            "dii": {
                "buy_value": "15,672.48",
                "sell_value": "11,234.56",
                "net_value": "4437.92",
                "date": "07-Feb-2026",
            },
            "date": "07-Feb-2026",
            "source": "NSE (Demo)",
        },
        "news": {
            "Moneycontrol": [
                {"title": "Nifty 50 closes above 23,400 as banking stocks rally; Sensex gains 465 points",
                 "link": "#", "published": "08 Feb 2026 03:45 PM", "source": "Moneycontrol",
                 "summary": "Indian benchmark indices closed higher on Friday, led by gains in banking and financial stocks."},
                {"title": "RBI keeps repo rate unchanged at 6.5% for 10th consecutive time",
                 "link": "#", "published": "08 Feb 2026 02:30 PM", "source": "Moneycontrol",
                 "summary": "The Reserve Bank of India maintained its key lending rate amid balanced inflation outlook."},
                {"title": "HDFC Bank Q3 results: Net profit rises 18% YoY to Rs 17,258 crore",
                 "link": "#", "published": "08 Feb 2026 01:15 PM", "source": "Moneycontrol",
                 "summary": "HDFC Bank reported strong quarterly earnings beating analyst estimates."},
                {"title": "Reliance Industries plans Rs 75,000 crore capex for new energy business",
                 "link": "#", "published": "08 Feb 2026 11:30 AM", "source": "Moneycontrol",
                 "summary": "RIL to invest heavily in green hydrogen, solar manufacturing and battery storage."},
                {"title": "Adani Group stocks surge as FPIs increase holdings in Q3",
                 "link": "#", "published": "08 Feb 2026 10:45 AM", "source": "Moneycontrol",
                 "summary": "Foreign portfolio investors raised their stake in several Adani Group companies."},
            ],
            "Economic_Times_Markets": [
                {"title": "IT stocks rally as US tech earnings boost sentiment; TCS, Infosys gain",
                 "link": "#", "published": "08 Feb 2026 03:20 PM", "source": "Economic_Times_Markets",
                 "summary": "IT sector index gains 0.75% as positive cues from US tech sector."},
                {"title": "Gold prices hit record high of Rs 72,500 per 10 grams on safe-haven demand",
                 "link": "#", "published": "08 Feb 2026 02:00 PM", "source": "Economic_Times_Markets",
                 "summary": "Gold continues its upward rally amid global geopolitical tensions."},
                {"title": "PSU bank stocks in focus: BoB, PNB surge on strong Q3 numbers",
                 "link": "#", "published": "08 Feb 2026 12:45 PM", "source": "Economic_Times_Markets",
                 "summary": "Public sector banks report improved asset quality and higher profits."},
                {"title": "Tata Motors DVR premium narrows; stock up 3% on strong JLR sales",
                 "link": "#", "published": "08 Feb 2026 11:00 AM", "source": "Economic_Times_Markets",
                 "summary": "Jaguar Land Rover reports best monthly sales in UK and Europe."},
            ],
            "LiveMint": [
                {"title": "Budget 2026 impact: Defence stocks surge as government hikes allocation by 15%",
                 "link": "#", "published": "08 Feb 2026 03:00 PM", "source": "LiveMint",
                 "summary": "Defence sector allocation increased to Rs 6.5 lakh crore."},
                {"title": "Pharma sector outperforms as FDA approvals boost sentiment",
                 "link": "#", "published": "08 Feb 2026 01:30 PM", "source": "LiveMint",
                 "summary": "Sun Pharma, Dr Reddy's and Cipla lead gains in pharma space."},
                {"title": "Rupee strengthens to 84.20 against dollar on FII inflows",
                 "link": "#", "published": "08 Feb 2026 12:00 PM", "source": "LiveMint",
                 "summary": "Indian rupee gains 15 paise against the US dollar."},
            ],
            "NDTV_Profit": [
                {"title": "Mutual fund SIP inflows hit record Rs 22,000 crore in January 2026",
                 "link": "#", "published": "08 Feb 2026 02:45 PM", "source": "NDTV_Profit",
                 "summary": "Systematic investment plan inflows continue their upward trajectory."},
                {"title": "Smallcap index underperforms; experts warn of frothy valuations",
                 "link": "#", "published": "08 Feb 2026 01:00 PM", "source": "NDTV_Profit",
                 "summary": "Smallcap stocks see selling pressure as valuations appear stretched."},
            ],
            "Business_Standard": [
                {"title": "SEBI tightens F&O rules; minimum lot size increased to Rs 15 lakh",
                 "link": "#", "published": "08 Feb 2026 03:30 PM", "source": "Business_Standard",
                 "summary": "New derivatives rules to be effective from April 2026."},
                {"title": "Coal India declares interim dividend of Rs 15 per share",
                 "link": "#", "published": "08 Feb 2026 11:15 AM", "source": "Business_Standard",
                 "summary": "Coal India board approves interim dividend for FY26."},
            ],
        },
        "raw_recommendations": [
            # --- Stocks recommended by MULTIPLE sources (will rank highest) ---
            {"stock": "HDFC Bank", "recommendation": "Buy", "target_price": "1,950",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy HDFC Bank target price Rs 1,950"},
            {"stock": "HDFC Bank Ltd", "recommendation": "Buy", "target_price": "2,000",
             "source": "Economic Times", "type": "buy", "headline": "HDFC Bank: Accumulate for long term wealth creation"},
            {"stock": "HDFC Bank", "recommendation": "Outperform", "target_price": "1,980",
             "source": "Trendlyne", "type": "buy", "headline": "25 analysts recommend Buy on HDFC Bank"},

            {"stock": "Reliance Industries", "recommendation": "Buy", "target_price": "3,100",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy Reliance Industries target Rs 3,100"},
            {"stock": "Reliance Industries Ltd", "recommendation": "Buy", "target_price": "3,200",
             "source": "Economic Times", "type": "buy", "headline": "Reliance Industries: Strong Buy for long term"},
            {"stock": "Reliance Industries", "recommendation": "Buy", "target_price": "3,150",
             "source": "Trendlyne", "type": "buy", "headline": "30 analysts recommend Buy"},

            {"stock": "Infosys", "recommendation": "Buy", "target_price": "1,950",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy Infosys for short term target 1950"},
            {"stock": "Infosys Ltd", "recommendation": "Buy", "target_price": "2,000",
             "source": "Economic Times", "type": "buy", "headline": "Infosys: Momentum breakout, intraday buy above 1880"},
            {"stock": "Infosys", "recommendation": "Buy", "target_price": "1,975",
             "source": "Trendlyne", "type": "buy"},

            {"stock": "TCS", "recommendation": "Buy", "target_price": "4,200",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy TCS target Rs 4,200"},
            {"stock": "TCS", "recommendation": "Buy", "target_price": "4,350",
             "source": "Trendlyne", "type": "buy", "headline": "22 analysts recommend Buy on TCS"},

            {"stock": "ICICI Bank", "recommendation": "Buy", "target_price": "1,350",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy ICICI Bank for intraday target 1350"},
            {"stock": "ICICI Bank", "recommendation": "Buy", "target_price": "1,400",
             "source": "Economic Times", "type": "buy", "headline": "ICICI Bank: Accumulate for long term portfolio"},
            {"stock": "ICICI Bank", "recommendation": "Buy", "target_price": "1,380",
             "source": "Trendlyne", "type": "buy"},

            {"stock": "Bharti Airtel", "recommendation": "Buy", "target_price": "1,750",
             "source": "Moneycontrol", "type": "buy", "headline": "Bharti Airtel: Buy for long term multibagger potential"},
            {"stock": "Bharti Airtel", "recommendation": "Buy", "target_price": "1,800",
             "source": "Trendlyne", "type": "buy", "headline": "18 analysts recommend Buy"},

            {"stock": "Larsen & Toubro", "recommendation": "Buy", "target_price": "4,100",
             "source": "Economic Times", "type": "buy", "headline": "L&T: Buy for long term growth portfolio target 4100"},
            {"stock": "L&T", "recommendation": "Buy", "target_price": "4,050",
             "source": "Trendlyne", "type": "buy"},

            {"stock": "Sun Pharma", "recommendation": "Buy", "target_price": "1,850",
             "source": "Moneycontrol", "type": "buy", "headline": "Sun Pharma: Breakout today, intraday buy"},
            {"stock": "Sun Pharma", "recommendation": "Buy", "target_price": "1,900",
             "source": "Economic Times", "type": "buy", "headline": "Sun Pharma: Strong momentum, short term buy"},

            {"stock": "SBI", "recommendation": "Buy", "target_price": "870",
             "source": "Moneycontrol", "type": "buy", "headline": "Buy SBI for intraday session target 870"},
            {"stock": "State Bank of India", "recommendation": "Buy", "target_price": "900",
             "source": "Trendlyne", "type": "buy"},

            {"stock": "Tata Motors", "recommendation": "Buy", "target_price": "820",
             "source": "Economic Times", "type": "buy", "headline": "Buy Tata Motors target 820 for short term swing trade"},

            {"stock": "ITC", "recommendation": "Buy", "target_price": "510",
             "source": "Moneycontrol", "type": "buy", "headline": "ITC: Accumulate for long term value, undervalued quality stock"},
            {"stock": "ITC", "recommendation": "Accumulate", "target_price": "525",
             "source": "Trendlyne", "type": "buy", "headline": "ITC: Fundamental value pick for long term wealth creator"},

            {"stock": "Bajaj Finance", "recommendation": "Buy", "target_price": "8,200",
             "source": "Economic Times", "type": "buy",
             "headline": "Bajaj Finance breakout: Intraday momentum buy above 7900"},

            {"stock": "Axis Bank", "recommendation": "Buy", "target_price": "1,250",
             "source": "Moneycontrol", "type": "buy", "headline": "Axis Bank: Buy for today's session, immediate target 1250"},

            {"stock": "Hindustan Unilever", "recommendation": "Hold", "target_price": "2,700",
             "source": "Trendlyne", "type": "hold"},

            {"stock": "Wipro", "recommendation": "Buy", "target_price": "570",
             "source": "Moneycontrol", "type": "buy", "headline": "Wipro: Gap up expected, intraday buy"},

            {"stock": "Coal India", "recommendation": "Buy", "target_price": "530",
             "source": "Economic Times", "type": "buy", "headline": "Coal India: Buy for long term, strong dividend yield"},

            {"stock": "Power Grid Corp", "recommendation": "Buy", "target_price": "340",
             "source": "Trendlyne", "type": "buy", "headline": "Power Grid: Undervalued infrastructure play"},
        ],
        "results": [
            {"company": "Tata Consultancy Services", "date": "10-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Hindustan Unilever", "date": "11-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Bajaj Auto", "date": "12-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Nestle India", "date": "12-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Titan Company", "date": "14-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Britannia Industries", "date": "14-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Adani Ports", "date": "17-Feb-2026", "period": "Q3 FY26", "source": "Moneycontrol"},
            {"company": "Cipla", "date": "17-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Godrej Consumer Products", "date": "18-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
            {"company": "Bharat Electronics", "date": "19-Feb-2026", "period": "Q3 FY26", "source": "BSE"},
        ],
        "dividends": [
            {"company": "Coal India Ltd", "ex_date": "14-Feb-2026", "dividend_amount": "Rs 15.00 per share", "record_date": "14-Feb-2026"},
            {"company": "NTPC Ltd", "ex_date": "18-Feb-2026", "dividend_amount": "Rs 4.25 per share", "record_date": "18-Feb-2026"},
            {"company": "Power Grid Corp", "ex_date": "20-Feb-2026", "dividend_amount": "Rs 5.00 per share", "record_date": "20-Feb-2026"},
            {"company": "Oil & Natural Gas Corp", "ex_date": "21-Feb-2026", "dividend_amount": "Rs 6.50 per share", "record_date": "21-Feb-2026"},
            {"company": "Indian Oil Corporation", "ex_date": "25-Feb-2026", "dividend_amount": "Rs 7.00 per share", "record_date": "25-Feb-2026"},
            {"company": "Bharat Petroleum", "ex_date": "27-Feb-2026", "dividend_amount": "Rs 10.00 per share", "record_date": "27-Feb-2026"},
            {"company": "Vedanta Ltd", "ex_date": "28-Feb-2026", "dividend_amount": "Rs 20.50 per share", "record_date": "28-Feb-2026"},
            {"company": "Hindustan Zinc", "ex_date": "03-Mar-2026", "dividend_amount": "Rs 12.00 per share", "record_date": "03-Mar-2026"},
        ],
        "bonus": [
            {"company": "Tata Elxsi Ltd", "ex_date": "20-Feb-2026", "ratio": "1:1 (1 share for every 1 held)", "record_date": "20-Feb-2026", "type": "Bonus"},
            {"company": "Angel One Ltd", "ex_date": "25-Feb-2026", "ratio": "1:2 (1 share for every 2 held)", "record_date": "25-Feb-2026", "type": "Bonus"},
            {"company": "Nippon Life India AMC", "ex_date": "28-Feb-2026", "ratio": "1:1 (1 share for every 1 held)", "record_date": "28-Feb-2026", "type": "Bonus"},
            {"company": "Happiest Minds Tech", "ex_date": "05-Mar-2026", "ratio": "FV split from Rs 10 to Rs 2", "record_date": "05-Mar-2026", "type": "Split"},
            {"company": "IRCTC", "ex_date": "10-Mar-2026", "ratio": "FV split from Rs 10 to Rs 5", "record_date": "10-Mar-2026", "type": "Split"},
        ],
        "ipos": {
            "open": [
                {"name": "Hexaware Technologies IPO", "date": "07 Feb - 11 Feb 2026", "size": "Rs 8,750 Cr", "price_band": "Rs 674 - Rs 708"},
                {"name": "Ather Energy IPO", "date": "08 Feb - 12 Feb 2026", "size": "Rs 3,100 Cr", "price_band": "Rs 321 - Rs 336"},
            ],
            "upcoming": [
                {"name": "LG Electronics India IPO", "date": "Feb 2026", "size": "Rs 15,000 Cr", "price_band": "TBA"},
                {"name": "Boat (Imagine Marketing) IPO", "date": "Mar 2026", "size": "Rs 2,000 Cr", "price_band": "TBA"},
                {"name": "PhysicsWallah IPO", "date": "Mar 2026", "size": "Rs 4,500 Cr", "price_band": "TBA"},
                {"name": "Tata Capital IPO", "date": "Q1 FY27", "size": "Rs 12,000 Cr", "price_band": "TBA"},
            ],
            "recently_listed": [
                {"name": "Dr Agarwals Eye Hospital", "date": "31 Jan 2026", "size": "Rs 3,027 Cr", "price_band": "Listed at Rs 445 (12% premium)"},
                {"name": "Mobiletron Electronics", "date": "28 Jan 2026", "size": "Rs 550 Cr", "price_band": "Listed at Rs 168 (8% premium)"},
            ],
        },
    }
